version: "3.8"

services:
    app:
        build: .
        container_name: ashraya
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        environment:
            - 
        depends_on:
            - db

    db:
        # image: postgres:15
        # container_name: recruitlens_db
        # environment:
        #     - POSTGRES_USER=postgres
        #     - POSTGRES_PASSWORD=postgres
        #     - POSTGRES_DB=recruitlens
        # ports:
        #     - "5432:5432"
        # volumes:
        #     - postgres_data:/var/lib/postgresql/data

# volumes:
#     postgres_data:
